language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - ia32-libs
cache:
  directories:
  - "$HOME/.m2"
before_install: 
  - git clone -b travis `git config --get remote.origin.url` target/travis
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U --settings target/travis/settings.xml
script: mvn test -B --settings target/travis/settings.xml
after_success: mvn clean deploy --settings target/travis/settings.xml -DskipTests=true
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
env:
  global:
  - secure: TcAPj8QjCqouo+vD9EDbp2WWR9RalfBHra+VIMI1tzYZM+Kkr9wmOLvOL/hS1REiCLKEon1gxlJLRXj2xqwwPJyjVdzOzMX5Kfu5XoiJxfsdcQqJsAzbH4Z9xJGKq9GlcuPGM4/ZM8VPQDI5aEz44JnxP4jnh81XQk+2z+dKtfDfr82YnRdxgCwgmARHgB9fDjbUW1rSWWrgjcUdqmitID0Y6qiW0U8KVE+MPEWjOAQ+PK0HthNwkTqLdcan9IMrA/UFRjmYOA95pCC1/cnxpd4GztNMeeVggYwsM8kzaaS5cSm8KjKeoYPzkp17+9KnDFheX0g8I65MYWKTY7xx4ZxSthjDxAuU4gGgSYsPANaJrGwOODniaCBpkZ1dFEt5gmoC16SzvNFsWZkII1t6G0CyPYljzq/iqd7HHEX+Mi/ybV9CW2F3ysjA4GKsN2g65bl+Cjeyhsl35f1pT7kPab9jm7T3HPInpdLmH4vRJ80WUgn1bi12V6fFuBnWpLv56ndM+Gq5fE6mDre8219vIQQDxWYTcxGH9LTERz3HjILid4SoPj1wQtFMbzxwf+pt3qGnw/+glYvD9joMNWrjhcJwbVF0ePjY3oOld16bhuM3zzksVPSvfhrFb5shKDidM61hlHSx/rSrds6IhKcCjAL/TGXjqtYbZ1y3Kx5jhuo=
  - secure: ZBSlrBlow4An6DpXxysKd0A+HDL/2HKxukDBqkfpm7Jr0jOTcK2VHYG5GjMdU/yx4DN8RpuvpGG5a7mPjaySlm5oKqPCdnIFRRa3gDkP/XkfMWeQP6PDh7wiXfkqqaGRlO4yZ2xJyKjqvMK5Xn7J9IDt+D0uGfMJvo+fLjYYCSzC3Oa7E/2inqE/sCvqo3mNKsFYjhRpxiuq0MRiECoMc+zTXeazI5Y/WOrF2PDo8+Z6Pp4iQdys1r+tWdHLgd4LgY3qKWicZhRmKZRZP/4Jjy2wpnfgsmiaUDT2xYVDcqj42j7rfQGoCsjBSCKpDNZSIFKtMbSEl9tNCeEVZ1gqKUVdPXxYg6/x6uOTNBeHKLaMCt9yBLSWWfSe6MsKLY+wCjjVW0v1pQ+dB3h3FgAozlK7H8Wx8mJuezH52JgfP92ArdR5nD5jsitc01c7G9GLnW15WXFd8cvgt8rCScGR6OFsfk/dJE85b5/J6z0RstrPm6GJJkRU+Icv2W8J56TA0B3dRuQCRfIzVbUpWOt02zis/mw8z4S0Bln7AVYZW4NniafSjIPbelXI0f+mMhRrm5rW0CsbEd++S2h3S7ILYaqhl6KohwQKoqeDppoqjhja6FzCZX9lItFyi4eoExLpKp3E8QpFnHJl7EU9wcIGm5OwUMQ5HfJC54BwqYzUWTY=
